app = "phonebook-backend"
primary_region = "hel"

[build]
  image = "flyio/node"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
